pipeline{
    agent any

    stages{
        stage("Deploy"){
           steps {
               sh '''
               oc project hxwtvz-deploy-strategies
               oc start-build greeting-service --follow --wait
               '''        
            }
        }

        // Add the "Deploy" stage here
    }
}
